apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-gpu
  labels:
    name: ubuntu-gpu
spec:
  containers:
  - name:  ubuntu-gpu
    image: nvidia/cuda
    command:
      - sleep
      - infinity
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPU
