apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - sleep
        - infinity
      volumeMounts:
      - mountPath: /shared_volume
        name: site-data
  volumes:
  - name: site-data
    persistentVolumeClaim:
      claimName: pvc-nfs-caperez-lamp
