apiVersion: v1
kind: Pod
metadata:
  name: pytorch-v3
  labels:
    name: pytorch-v3
spec:
  containers:
  - name: pytorch-v3
    image: kbobrowski/deep-learning-essentials
    ports:
        - containerPort: 8888
    command:
    - sleep
    - infinity
    volumeMounts:
        - mountPath: /data
          name: data
          subPath: devos
    resources:
      limits:
        nvidia.com/gpu: 1
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: lca4-scratch