apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    name: ubuntu
spec:
  containers:
    - name: ubuntu
      image: nvidia/cuda
      ports:
        - containerPort: 80
      command:
        - sleep
        - infinity
      volumeMounts:
        - mountPath: /data
          name: data
          subPath: devos
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: lca4-scratch